### ISSUE TITLE
Serial Monitor showing gibberish data

### ISSUE THREAD

**Issue by pipipipi2002** [scottbez1/smartknob#111]
I managed to flash the firmware into the ESP32, but when im monitoring the serial, it gives me gibberish data.
<img width="1013" alt="Screenshot 2023-02-27 at 01 46 03" src="https://user-images.githubusercontent.com/65348889/221427125-58a76f9f-81fe-4fc7-9317-b3a4dacee89f.png">

I cloned the code directly from github and uploaded, according to the guide provided by scott. Thank you in advance!

**Comment by staalebk** [comment]
Did you set the correct baud rate? I think the default for this project is 921 600.

**Comment by ChristianEmeis** [comment]
Might be a little bit late, but from your screenshot, I can see that your serial monitor is running at the correct default baud rate of 921600. From 2 Smartknobs I have one with a similar issue, changing the baud rate to 115200 fixed it for me, but I'm not sure what’s the root cause of this problem, as it worked with 921600 before. To change the baud rate, go to your platform.ini file and under base_config change monitor_speed and DMONITOR_SPEED under build_flags to your desired baud rate.

**Comment by pipipipi2002** [comment]
Hmm that seems to have solved the problem. Thank you very much.
