### ISSUE TITLE
Idea: Add ethernet port with Poe support

### ISSUE THREAD

**Issue by SantiagoSotoC** [scottbez1/smartknob#51]
I think adding support for ethernet with poe can help in cases where latency is important, it also makes power distribution easier.

It may not be convenient in all cases, therefore I propose to create two versions, the normal one and the one with ethernet and poe support.

**Comment by scottbez1** [comment]
Thanks for the suggestion!

There was some previous discussion in #14 - currently there are technical constraints (lack of GPIO on the ESP32 - see https://github.com/scottbez1/smartknob/issues/14#issuecomment-1066191512) and I also want to keep this project *extremely* focused for now (priority 1 is finding a new motor and updating the design for it, and priority 2 is supporting/troubleshooting/helping people who managed to find motors and are currently building one), so to be quite frank, I don't see PoE being implemented any time soon.

However, since you are the second person to bring this up, I will reopen #14 as a general thread for ethernet/PoE discussion in case anyone has some interesting ideas that would make it a no-brainer to add.

(closing in favor of keeping #14 for ongoing discussion)
