### ISSUE TITLE
Version of KiCad, upgrade to KiCad 6.0.5?

### ISSUE THREAD

**Issue by KSturgis** [scottbez1/smartknob#77]
What version of KiCad was used to create the schematics? Is there a blocking issue with upgrading to the latest 6.0.5? 

I noticed that electronics/scripts/dependencies.sh KiCad 5.1 is used in the CD deployment. When I try and open a schematic in KiCad Win 5.1 there is an issue with 'older symbol libraries' that I am not sure how to fix.

Any help would be appreciated.

**Comment by scottbez1** [comment]
When I first set up the CI pipeline I believe KiBot support for 6 wasn't stable/released. I would have preferred to use KiCad 6 for this project, but that was a blocker for me at the time (solid CI is more important than having the latest features from 6, IMO).

Given that KiCad 5 is not _that_ old, and the electronics are somewhat stable for now, migrating to KiCad 6 is not a high priority for me personally at the moment (I'm focusing entirely on tracking down and getting good motors available at the moment, and then firmware improvements after that), but I would be open to a PR in the meantime that updates to 6 so long as the CI pipeline is updated and fully tested on a fork.

If you can share any more details about the older symbol libraries issue I'd be happy to dig in further though (it's possible I have something misconfigured in the project, otherwise I would expect a 5 project _should_ open alright in 6)

**Comment by scottbez1** [comment]
Designs were updated to KiCad 6 in #96
